// Generated by scripts/gen-version.mjs from git at build time.
// Do not edit by hand. Run `npm run build` (or `npm run dev`) to refresh.
export const APP_VERSION = "0.1.15";
export const APP_BUILD = 40;
export const APP_COMMIT = "4746aa5";
export const APP_BUILD_DATE = "2026-08-08";
