// Generated by scripts/gen-version.mjs from git at build time.
// Do not edit by hand. Run `npm run build` (or `npm run dev`) to refresh.
export const APP_VERSION = "0.1.0";
export const APP_BUILD = 31;
export const APP_COMMIT = "d68b5b6";
export const APP_BUILD_DATE = "2026-08-05";
