// Generates src/lib/version.ts from package.json and git at build time.
//
// The build number is the git commit count, so it only moves forward when there
// is a new commit. A rebuild without a new commit rewrites the same bytes and
// leaves the working tree clean, which keeps `git status` quiet during local
// rebuilds. When git is absent (a tarball checkout, a container without git),
// every field falls back to a placeholder so the build never breaks.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));

function git(args) {
  try {
    return execSync(`git ${args}`, { encoding: "utf8", cwd: root, stdio: ["pipe", "pipe", "ignore"] }).trim();
  } catch {
    return "";
  }
}

const commitCount = git("rev-list --count HEAD");
const commit = git("rev-parse --short HEAD");
const commitDate = git("show -s --format=%cI HEAD");

const build = commitCount ? Number(commitCount) : 0;
// %cI is ISO 8601 strict (e.g. 2026-08-03T17:43:01+09:00); take the date half so
// the About line reads "built 2026-08-03" rather than a wall of timezone.
const date = commitDate ? commitDate.slice(0, 10) : "";

const content = `// Generated by scripts/gen-version.mjs from git at build time.
// Do not edit by hand. Run \`npm run build\` (or \`npm run dev\`) to refresh.
export const APP_VERSION = ${JSON.stringify(pkg.version)};
export const APP_BUILD = ${build};
export const APP_COMMIT = ${JSON.stringify(commit)};
export const APP_BUILD_DATE = ${JSON.stringify(date)};
`;

writeFileSync(resolve(root, "src/lib/version.ts"), content, "utf8");

console.log(`version: ${pkg.version} (build ${build}, ${commit || "no git"})`);